import Head from 'next/head'
import { GetStaticProps } from 'next';
import styles from '../styles/movies.module.css'
import Link from 'next/link'
import React, { FC, useMemo, useState } from 'react';
import { moviesType } from '@/types/types';
import { useRouter } from 'next/router';

export const getStaticProps:GetStaticProps = async () => {
  const response = await fetch('https://www.omdbapi.com/?&apikey=9ae0df05&s=fast');
  const data = await response.json();
  
  if(!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: { movies: data.Search},
  }
};

type moviesTypeProps = {
  movies: [moviesType]
}

const Home:FC<moviesTypeProps> = React.memo(({movies}) => {
  const [value, setValue] = useState<string>('');
  const [hint, setHint] = useState<Boolean>(false);
  const [searchMovies, setSearchMovies] = useState<moviesType[]>(movies);
  const router = useRouter();

  useMemo(() => {
    if(value.length > 2){
      setHint(false)
    } else if(value.length === 0) {
      setHint(false)
    } else if (value.length > 0 && value.length <= 2){
      setHint(true)
    }
  }, [value])

  async function pressEnter(event: React.KeyboardEvent<HTMLInputElement>, value:string) {
    if(event.code === "Enter" && value.length > 2) {
      const response = await fetch(`https://www.omdbapi.com/?&apikey=9ae0df05&s=${value}`);
      if(response.ok) {
        const data = await response.json();
        setSearchMovies(data.Search)
      } else {
        router.push('/404');
      }
    } 
  }

  return (
    <>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className='main'>
        <div className='main__container container'>
          <h1 className={styles.main__title}>Search movies</h1>
          <div className={styles.main__row}>
            <div className={styles.main__input}>
              <input  
                onKeyDown={e => pressEnter(e, value)}
                onChange={e => setValue(e.target.value)}
                className={`${styles.input} ${hint ? styles.input__err : ''}`} 
                id='movie-input' 
                type="text" 
                placeholder='write movie name and press enter' 
              />
              <span 
                className={`${styles.hint} ${hint ? styles.hint__show : styles.hint__hide}`}
              >
                Minimum number of characters is 3
              </span>
            </div>
          </div>
          {!searchMovies && <h2 className={styles.not__found}>Movies not found</h2>}
          {searchMovies && <div className={styles.main__movies}>
            {movies && searchMovies.map(({ imdbID, Title, Poster, Year }) => (
              <article className={styles.article} key={imdbID}>
                <div className={styles.ibg}>
                  <img src={Poster} alt='Poster to film'/>
                </div>
                <Link href={`/${imdbID}`} className={styles.movie__link}>{Title}</Link>
                <h3 className={styles.movie__year}>Release: {Year}</h3>
              </article>
            ))}
          </div>}
        </div>
      </main>
    </>
  )
});

export default Home;